source 'https://rubygems.org'
source 'https://gem.fury.io/engineerai'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.5'
gem 'rails', '~> 6.1.7'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'bx_block_login-3d0582b5', '1.0.1', require: 'bx_block_login'
gem 'bx_block_forgot_password-4de8968b', '0.0.6', require: 'bx_block_forgot_password'
gem 'account_block', '1.3.0'
gem 'bx_block_sms', '0.0.5'
gem 'bx_block_data_import_export-ec567cbb', '1.0.2'
gem 'bx_block_navmenu-1cdc25a4', '1.1.0', require: 'bx_block_navmenu'
gem 'bx_block_push_notifications-c0f9e9b7', '1.1.1'
gem 'bx_block_categories-acd0763f', '1.1.0', require: 'bx_block_categories'
gem 'bx_block_surveys', '0.1.0'
gem 'bx_block_account_groups', '1.1.0'
gem 'bx_block_admin', '1.1.0'
gem 'bx_block_roles_permissions-c50949d0', '1.1.0', require: 'bx_block_roles_permissions'
gem 'bx_block_terms_and_conditions', '1.1.0'
gem 'bx_block_filter_items-b1be1f37', '1.0.1', require: 'bx_block_filter_items'
gem 'bx_block_catalogue-0e5da613', '1.1.0', require: 'bx_block_catalogue'
gem 'bx_block_notifsettings-296428d4', '1.1.0', require: 'bx_block_notifsettings'
gem 'bx_block_addfriends', '0.1.3'
gem 'bx_block_contentflag', '0.1.2'
gem 'bx_block_stripe_integration', '2.0.0'
gem 'bx_block_order_management-674a3e38', '0.0.33', require: 'bx_block_order_management'
gem 'bx_block_coupon_cg-1da92412', '0.0.1', require: 'bx_block_coupon_cg'
gem 'bx_block_fedex_integration-c7604a00', '1.1.0', require: 'bx_block_fedex_integration'
gem 'bx_block_stripe_order_management', '0.3.0'
gem 'bx_block_inapppurchasing', '0.1.0'
gem 'bx_block_email_notifications', '1.1.0'
gem 'bx_block_recommendation', '0.1.4'
gem 'bx_block_help_centre', '1.1.0'
gem 'bx_block_content_management', '0.1.3'
gem 'bx_block_advanced_search-23b25188', '1.0.1', require: 'bx_block_advanced_search'
gem 'bx_block_custom_form-63cd533b', '1.1.0', require: 'bx_block_custom_form'
gem 'bx_block_block_users-eefa7b2b', '1.1.0', require: 'bx_block_block_users'
gem 'bx_block_bulk_uploading', '1.1.0', require: 'bx_block_bulk_uploading'
gem 'bx_block_chat', '1.1.0'
gem 'bx_block_joblisting', '0.1.5'
gem 'bx_block_notifications-a22eb801', '1.1.0', require: 'bx_block_notifications'
gem 'bx_block_share', '1.1.0'
gem 'bx_block_posts-3dc5b993', '1.1.0', require: 'bx_block_posts'
gem 'bx_block_activity_feed', '1.1.0', require: 'bx_block_activity_feed'
gem 'bx_block_like', '1.1.0'
gem 'bx_block_comments-568532a5', '1.2.0'
gem 'bx_block_profile', '1.1.0'
gem 'bx_block_profile_bio', '1.1.1'
gem 'bx_block_favourites', '1.1.0'
gem 'bx_block_location-99004202', '0.0.10', require: 'bx_block_location'
gem 'bx_block_address-07f1bf4f', '1.1.0', require: 'bx_block_address'
gem 'bx_block_appointment_management-eb816fd3', '1.1.0', require: 'bx_block_appointment_management'
gem 'bx_block_request_management', '1.1.0'
gem 'bx_block_subscription_billing', '1.1.0'
gem 'bx_block_settings-5412d427', '1.1.0', require: 'bx_block_settings'
gem 'bx_block_like_a_post-27907772', '0.0.6', require: 'bx_block_like_a_post'
gem 'bx_block_payment_admin', '1.1.0'
gem 'bx_block_content_moderation', '0.1.1'
gem 'bx_block_projectreporting', '0.1.5'
gem 'builder_base', '1.6.1'
group :development, :test do
    gem 'rspec-sonarqube-formatter', '1.5.0'
    gem 'rspec-rails', '5.1.2'
    gem 'simplecov', '0.17.0'
    gem 'dotenv-rails'
    gem 'faker'
end

group :test do
  gem 'mock_redis', '0.34.0'
  gem 'shoulda-matchers'
  gem 'factory_bot_rails', '6.2.0'
end

gem 'sidekiq_alive'
gem 'sidekiq', '~> 6.1.0'

gem "yabeda-prometheus"    # Base
gem "yabeda-rails"         #API endpoint monitoring
gem "yabeda-http_requests" #External request monitoring
gem "yabeda-puma-plugin"
gem 'yabeda-sidekiq'

gem 'bx_block_cors'
# Builder analytics
gem 'bx_block_analytics'
gem 'bx_block_builder_analytics'
gem 'devise'
gem 'sassc-rails'
gem 'activeadmin'
gem 'active_admin_role'
gem 'activeadmin_json_editor'
gem 'active_admin_datetimepicker'
gem 'arctic_admin'
gem 'activeadmin_quill_editor'
gem 'will_paginate'
gem 'kaminari'
gem 'rack-cors'
gem 'activestorage-validator'
gem 'bx_block_wishlist', '0.1.1'
gem 'bx_block_reviews', '1.1.0', require: 'bx_block_reviews'
gem 'rails-controller-testing'
gem 'sidekiq-cron'
gem 'deep_cloneable'
gem 'redis', '~> 4.8.0'
gem 'sidekiq-scheduler'
gem 'ffi', '~> 1.16' 
gem 'active_storage_validations', '1.1.0'
gem 'profanity', require: 'profanity_filter'
gem 'profanity_filter'
gem 'ruby-openai', '~> 6.3.0'
gem 'image_processing', '~> 1.2'
gem 'streamio-ffmpeg'